##Practice on DRY code

**Author:** Katy Sill

**Date:** August 20th, 2018

**Import Python Packages** *Import necessary packages including numpy, pandas, os, urllib.request and matplotlib.pyplot

In [57]:
import numpy as np
import pandas as pd
import os
import urllib.request
import matplotlib.pyplot as plt

**Get data and import into numpy arrays and pandas dataframes**

In [58]:
# first set working directory
os.chdir("C:/users/sill/earth-analytics-bootcamp/")

# download data from figshare
urllib.request.urlretrieve(url="https://ndownloader.figshare.com/files/12807380",
                          filename = "data/monthly-precip-1988-to-1992.csv")
urllib.request.urlretrieve(url="https://ndownloader.figshare.com/files/12807383",
                          filename = "data/monthly-precip-1993-to-1997.csv")

# print message that data downloads were successful
print("datasets downloaded successfully")

datasets downloaded successfully


In [59]:
# then load data into numpy arrays 
monthly_precip_1988_to_1992 = np.loadtxt(fname= "C:/users/sill/earth-analytics-bootcamp/data//monthly-precip-1988-to-1992.csv", delimiter = ",")
monthly_precip_1993_to_1997 = np.loadtxt(fname = "C:/users/sill/earth-analytics-bootcamp/data/monthly-precip-1993-to-1997.csv", delimiter = ",")

print(monthly_precip_1988_to_1992)
print(monthly_precip_1993_to_1997)

[[0.4  1.14 2.53 1.48 3.7  0.7  0.71 1.33 2.02 0.03 0.75 2.16]
 [1.19 1.27 0.97 1.95 2.68 2.93 1.43 1.63 3.54 1.4  0.09 1.54]
 [1.04 1.32 4.55 2.16 1.73 0.39 4.23 1.13 1.84 0.96 1.6  0.75]
 [1.05 0.15 0.43 2.41 2.9  3.59 3.11 2.08 1.21 0.93 3.3  0.01]
 [0.67 0.   5.17 0.46 1.7  0.96 1.13 3.08 0.02 0.79 2.56 0.84]]
[[0.25 0.9  2.15 2.56 1.73 3.38 1.4  1.04 3.32 2.42 2.17 0.55]
 [0.86 1.37 1.61 3.46 1.35 0.93 0.35 2.56 0.54 1.02 2.25 0.49]
 [0.64 1.53 1.21 5.45 9.59 4.03 0.72 1.45 2.96 0.59 1.51 0.25]
 [1.89 0.29 2.16 1.49 4.63 2.77 1.96 0.63 3.48 0.28 1.43 0.37]
 [0.87 1.83 0.91 5.77 2.19 3.69 1.14 5.27 1.92 2.7  1.52 0.68]]


In [64]:
urllib.request.urlretrieve(url = "https://ndownloader.figshare.com/files/12807389",
                        filename = "data/monthly-precip-1988-to-1992.csv")

urllib.request.urlretrieve(url = "https://ndownloader.figshare.com/files/12807386", 
                           filename = "data/temp-1996-to-2000-months.csv")

# print message that data downloads were successful
print("datasets downloaded successfully")

datasets downloaded successfully


In [65]:
# download data and import into pandas dataframes
temp_1991_to_1995_months = pd.read_csv("C:/users/sill/earth-analytics-bootcamp/data/monthly-precip-1988-to-1992.csv")
temp_1996_to_2000_months = pd.read_csv("C:/users/sill/earth-analytics-bootcamp/data/temp-1996-to-2000-months.csv")

# print dataframes
temp_1991_to_1995_months

Year  January  February  March  April   May  June  July  August  September  \
0  1991     29.9      40.9   42.8   47.8  58.2  66.6  70.5    69.2       61.7   
1  1992     35.9      40.6   43.3   54.3  59.1  62.9  68.3    66.3       64.4   
2  1993     28.3      30.6   42.4   47.6  57.5  64.5  69.5    67.3       58.8   
3  1994     35.5      31.9   43.9   47.6  60.8  70.0  71.2    70.9       65.0   
4  1995     34.5      38.3   42.1   45.1  50.9  62.4  70.5    74.0       60.4   

   October  November  December  
0     52.1      36.8      35.3  
1     54.1      34.1      29.2  
2     48.7      35.6      35.4  
3     50.6      36.6      36.1  
4     50.5      45.0      36.3

In [66]:
# print second dataframe with nice formatting
temp_1996_to_2000_months

Year  January  February  March  April   May  June  July  August  September  \
0  1996     29.7      37.7   37.9   50.4  58.9  66.9  71.5    69.5       60.8   
1  1997     31.3      32.8   45.5   42.8  57.4  66.5  71.4    68.7       64.0   
2  1998     36.5      36.4   38.7   46.5  58.8  62.1  72.8    70.7       67.1   
3  1999     36.4      42.1   46.0   44.5  55.6  64.8  73.5    69.3       58.5   
4  2000     36.4      41.0   42.9   51.2  61.0  67.4  74.7    73.0       63.1   

   October  November  December  
0     53.1      40.6      36.5  
1     52.7      37.9      33.9  
2     50.4      44.0      32.2  
3     51.9      48.0      36.9  
4     49.6      31.4      31.2

Question 1: Use Indexing to Select from Numpy Array

Select the second row of data (including all columns) from the numpy array containing the data for 1988 to 1992, and save to a new numpy array.

Name your new array appropriately to indicate the year of data that it represents.

In [67]:
monthly_precip_data_1989 = monthly_precip_1988_to_1992[1:2,:]
print(monthly_precip_data_1989)

[[1.19 1.27 0.97 1.95 2.68 2.93 1.43 1.63 3.54 1.4  0.09 1.54]]


Question 2: Write a Conditional Statement to Check Dimensions of Numpy Array

Write a conditional statement that checks whether the numpy array created in the previous question (i.e. the selection) is a one-dimensional numpy array.

Print a message stating whether or not the array is one-dimensional.

In [68]:
# conditional statement to verify if new numpy array is 1-dimensional

if monthly_precip_data_1989.ndim == 1:
    print("This is a one dimensional array")
    
else:
    print("This is not a one dimensional array, it has", monthly_precip_data_1989.ndim, "dimensions")

This is not a one dimensional array, it has 2 dimensions


Question 3: Expand Conditional Statement to Execute Different Code

Modify your conditional statement from the previous question, so that your if and else statements execute different code, not just printing messages.

For the if statement, rather than printing a message, print the shape of the numpy array from the previous question (i.e. the selection).

For the else statement, rather than printing a message, include the following code lines to be executed (i.e. if the array is not one-dimensional):

    arrayname_1d = arrayname.flatten()
    print(arrayname_1d.shape)

These code lines will flatten a numpy array (in this case named arrayname) to a one-dimensional array, save it to a new array called arrayname_1d, and print the shape of the new array.

In [69]:
# conditional statement to verify if new numpy array is 1-dimensional

if monthly_precip_data_1989.ndim == 1:
    print(monthly_precip_data_1989.shape)
    
else:
    monthly_precip_data_1989_1d = monthly_precip_data_1989.flatten()
    print(monthly_precip_data_1989_1d.shape)


(12,)


Question 4: Write a Conditional Statement to Check Dimensions of Two Numpy Arrays

Manually create a one-dimensional numpy array that contains the month names (i.e. January to December).

Write a conditional statement to check that this new array for month names has the same shape as the numpy array from the previous question (i.e. the selection).

Print a message stating whether are not these arrays have the same shape and can be plotted together.

In [70]:
# create numpy array with month names from Jan to Dec
months = np.array(["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"])

if months.ndim == monthly_precip_data_1989_1d.ndim:
    print("These arrays have the same dimensions and can be plotted together")
else:
    print("These arrays do NOT have the same dimensions and CANNOT be plotted together")

These arrays have the same dimensions and can be plotted together


Question 5: Practice Pseudo Coding

Reflect on your conditional statement from the previous question.

Write a sentence or two on how you could expand on your conditional statement from the previous question to create a plot from the two numpy arrays if they do indeed have the same shape.

Hint: what did you do in Question 3 to expand on your conditional statement?

In the if statement, you could include the code for plotting if the conditions were true, and then add the plotting code after flattening in the "else" statement.

ie, 
if monthly_precip_data_1989.ndim == 1:
        # just copy/paste plot code as placeholder for plotting
        plt.rcParams["figure.figsize"] = (8, 8)

        # create the plot space upon which to plot the data
        fig, ax = plt.subplots()
        
        # add the x-axis and the y-axis to the plot
        ax.plot(monthlist, boulder_precip_2007_to_2017[[year]], color="blue")
        
        # rotate x-axis by 45 degrees to improve readability
        plt.setp(ax.get_xticklabels(), rotation=45)

        # set plot title
        ax.set(title="Monthly Precipitation for " + year + " in Boulder, CO")

        # add labels to the axes
        ax.set(xlabel="Month", ylabel="Precipitation (mm)");print(monthly_precip_data_1989.shape)
    
else:
    monthly_precip_data_1989_1d = monthly_precip_data_1989.flatten()
    print(monthly_precip_data_1989_1d.shape)
    #then add plotting code


Question 6: Loop on Pandas Dataframes

Write a loop to run the info() method on the two pandas dataframes that you imported in this activity, and print the results.

Hint:

    Recall that creating a list of items to iterate upon is a good first step to writing a loop.
    Think about what you are iterating upon in this question - do your list values need "" to indicate text strings, or are you iterating on existing variables?

In [71]:
arraylist = [temp_1991_to_1995_months, temp_1996_to_2000_months]

for array in arraylist:
    print(array.info())
    print("")
    

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 13 columns):
Year         5 non-null int64
January      5 non-null float64
February     5 non-null float64
March        5 non-null float64
April        5 non-null float64
May          5 non-null float64
June         5 non-null float64
July         5 non-null float64
August       5 non-null float64
September    5 non-null float64
October      5 non-null float64
November     5 non-null float64
December     5 non-null float64
dtypes: float64(12), int64(1)
memory usage: 600.0 bytes
None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 13 columns):
Year         5 non-null int64
January      5 non-null float64
February     5 non-null float64
March        5 non-null float64
April        5 non-null float64
May          5 non-null float64
June         5 non-null float64
July         5 non-null float64
August       5 non-null float64
September    5 non-null float64
Octo

Question 7: Loop on Columns in Pandas Dataframes

Write a loop to run the .describe() method on each column in the pandas dataframe containing the data for 1996 to 2000).

Hint:

    Recall that creating a list of items to iterate upon is a good first step to writing a loop.
    Think about what you are iterating upon in this question - do your list values need "" to indicate text strings, or are you iterating on existing variables?
    Recall that to select columns in pandas dataframes using implicit variables (i.e. not explicitly created by you), change the syntax from dataframe.column_name to dataframe[[column_name]].

In [75]:
#create list of months
monthlist = ['January','February','March','April','May','June','July','August','September','October','November','December']

# use loop to calculate summary statistics for each month
for month in monthlist:
    
    summarystatistics = temp_1996_to_2000_months[[month]].describe()
    print(summarystatistics)
    print("")
    

         January
count   5.000000
mean   34.060000
std     3.298939
min    29.700000
25%    31.300000
50%    36.400000
75%    36.400000
max    36.500000

        February
count   5.000000
mean   38.000000
std     3.724916
min    32.800000
25%    36.400000
50%    37.700000
75%    41.000000
max    42.100000

           March
count   5.000000
mean   42.200000
std     3.760319
min    37.900000
25%    38.700000
50%    42.900000
75%    45.500000
max    46.000000

           April
count   5.000000
mean   47.080000
std     3.650616
min    42.800000
25%    44.500000
50%    46.500000
75%    50.400000
max    51.200000

           May
count   5.0000
mean   58.3400
std     1.9995
min    55.6000
25%    57.4000
50%    58.8000
75%    58.9000
max    61.0000

            June
count   5.000000
mean   65.540000
std     2.157081
min    62.100000
25%    64.800000
50%    66.500000
75%    66.900000
max    67.400000

            July
count   5.000000
mean   72.780000
std     1.391761
min    71.400000
25%    71

Question 8: Write Function to Summarize Numpy Array Using Axes

Write a function that calculates the mean across columns of a numpy array.

Hints:

    Recall which existing numpy function you can use to calculate a mean. You will include this function within the function you write to answer this question.
    Review the lessons on functions to see the use of axes to calculate a statistic across the rows or columns of a numpy array.

In [77]:
# function which calculates mean across columns
def mean_across_columns(x):
    # function accepts numpy arrays as inputs
    
    return(np.mean(x,axis = 0))

In [78]:
# call function to calculate mean for monthly precip from 1993 - 1997
mean_precip_1993_to_1997 = mean_across_columns(monthly_precip_1993_to_1997)
print(mean_precip_1993_to_1997)

[0.902 1.184 1.608 3.746 3.898 2.96  1.114 2.19  2.444 1.402 1.776 0.468]


Question 10: Practice Pseudo Coding

You have already learned how to save the output from one run of a function (see Question 9). What if you wanted to run the function on multiple numpy arrays?

Write a sentence or two on what you would need to know how to do, in order to save the output from a function that is running on multiple arrays in a loop.

Hint: think about how you can append values to a list using a loop (i.e. create an empty list that gets values appended to it in the loop).

You would need to know how to create a function that allowed for multiple inputs (the different numpy arrays) and also that allowed you to create multiple variables which could be called to return from the function (to output the multiple arrays which had been through the function). I think this is possible, but am not quite sure about the syntax. Perhaps you can have more than one variable in the function? For example def function(x,y,z) and then you could return(x), return(y) and return(z) after calculations had been performed?