# Practice with DRY code
<b>Author:</b> Mike Dorfman  
<b>Date:</b> August 20, 2018

Import necessary packages

In [2]:
import os
import urllib.request
import pandas as pd
import numpy as np

print("Imports successful")

Imports successful


Download files with urllib and import into numpy arrays

In [24]:
# Change directories to the data directory
os.chdir("../data")

# Download files from figshare to the data directory
urllib.request.urlretrieve(url="https://ndownloader.figshare.com/files/12807380", 
               filename="monthly-precip-1988-to-1992.csv")
urllib.request.urlretrieve(url="https://ndownloader.figshare.com/files/12807383", 
               filename="monthly-precip-1993-to-1997.csv")

# Import into numpy arrays
precip_mm_1988_to_1992 = np.loadtxt(fname="monthly-precip-1988-to-1992.csv", delimiter=",")
precip_mm_1993_to_1997 = np.loadtxt(fname="monthly-precip-1993-to-1997.csv", delimiter=",")
print(precip_mm_1988_to_1992)
print("")
print(precip_mm_1993_to_1997)

[[0.4  1.14 2.53 1.48 3.7  0.7  0.71 1.33 2.02 0.03 0.75 2.16]
 [1.19 1.27 0.97 1.95 2.68 2.93 1.43 1.63 3.54 1.4  0.09 1.54]
 [1.04 1.32 4.55 2.16 1.73 0.39 4.23 1.13 1.84 0.96 1.6  0.75]
 [1.05 0.15 0.43 2.41 2.9  3.59 3.11 2.08 1.21 0.93 3.3  0.01]
 [0.67 0.   5.17 0.46 1.7  0.96 1.13 3.08 0.02 0.79 2.56 0.84]]

[[0.25 0.9  2.15 2.56 1.73 3.38 1.4  1.04 3.32 2.42 2.17 0.55]
 [0.86 1.37 1.61 3.46 1.35 0.93 0.35 2.56 0.54 1.02 2.25 0.49]
 [0.64 1.53 1.21 5.45 9.59 4.03 0.72 1.45 2.96 0.59 1.51 0.25]
 [1.89 0.29 2.16 1.49 4.63 2.77 1.96 0.63 3.48 0.28 1.43 0.37]
 [0.87 1.83 0.91 5.77 2.19 3.69 1.14 5.27 1.92 2.7  1.52 0.68]]


Download files with urllib and import into pandas dataframes.

In [5]:
# Download files from figshare to the data directory
urllib.request.urlretrieve(url="https://ndownloader.figshare.com/files/12807389", 
               filename="temp-1991-to-1995-months.csv")
urllib.request.urlretrieve(url="https://ndownloader.figshare.com/files/12807386", 
               filename="temp-1996-to-2000-months.csv")


# Import first file into a pandas dataframe and print in tabular form# Import 
temp_f_1991_to_1995_pd = pd.read_csv("temp-1991-to-1995-months.csv")
temp_f_1991_to_1995_pd

Year  January  February  March  April   May  June  July  August  September  \
0  1991     29.9      40.9   42.8   47.8  58.2  66.6  70.5    69.2       61.7   
1  1992     35.9      40.6   43.3   54.3  59.1  62.9  68.3    66.3       64.4   
2  1993     28.3      30.6   42.4   47.6  57.5  64.5  69.5    67.3       58.8   
3  1994     35.5      31.9   43.9   47.6  60.8  70.0  71.2    70.9       65.0   
4  1995     34.5      38.3   42.1   45.1  50.9  62.4  70.5    74.0       60.4   

   October  November  December  
0     52.1      36.8      35.3  
1     54.1      34.1      29.2  
2     48.7      35.6      35.4  
3     50.6      36.6      36.1  
4     50.5      45.0      36.3

In [6]:
temp_f_1996_to_2000_pd = pd.read_csv("temp-1996-to-2000-months.csv")
temp_f_1996_to_2000_pd

Year  January  February  March  April   May  June  July  August  September  \
0  1996     29.7      37.7   37.9   50.4  58.9  66.9  71.5    69.5       60.8   
1  1997     31.3      32.8   45.5   42.8  57.4  66.5  71.4    68.7       64.0   
2  1998     36.5      36.4   38.7   46.5  58.8  62.1  72.8    70.7       67.1   
3  1999     36.4      42.1   46.0   44.5  55.6  64.8  73.5    69.3       58.5   
4  2000     36.4      41.0   42.9   51.2  61.0  67.4  74.7    73.0       63.1   

   October  November  December  
0     53.1      40.6      36.5  
1     52.7      37.9      33.9  
2     50.4      44.0      32.2  
3     51.9      48.0      36.9  
4     49.6      31.4      31.2

Subset the data to only get 1989.

In [9]:
# Get the second row (1989)
precip_mm_1989 = precip_mm_1988_to_1992[1]
print(precip_mm_1989)

[1.19 1.27 0.97 1.95 2.68 2.93 1.43 1.63 3.54 1.4  0.09 1.54]


Write a conditional to check the dimensions

In [10]:
if precip_mm_1989.ndim == 1:
    print("This is a one-dimensional array.")
else:
    print("This is NOT a one-dimensional array.")

This is a one-dimensional array.


Print the shape instead of just printing a message.

In [11]:
if precip_mm_1989.ndim == 1:
    print(precip_mm_1989.shape)
else:
    precip_mm_1989_1d = precip_mm_1989.flatten()
    print(precip_mm_1989.shape)

(12,)


Manually create a month name array and check to make sure it has the same dims as precip_mm_1989

In [13]:
# Manually create a numpy array with the full month names
jan_to_december_names = np.array(['January', 
                                  'February',
                                  'March',
                                  'April',
                                  'May',
                                  'June',
                                  'July',
                                  'August',
                                  'September',
                                  'October',
                                  'November',
                                  'December'])

# Make sure the shapes are the same
if jan_to_december_names.shape == precip_mm_1989.shape:
    print("These arrays have the same shape and can be plotted together.")

These arrays have the same shape and can be plotted together.


* Check to make sure they are the same shape
    * If they are, plot the shapes using this data  
    
...not sure if you want more detail here, but essentially paste the code in from homework 4 on plotting, indented for the conditional statement, replacing the title with an appropriate title and the data with jan_to_december_names and precip_mm_1989 with the data inputs.

In [14]:
dataframe_list = [temp_f_1991_to_1995_pd,
             temp_f_1996_to_2000_pd]

for dataframe in dataframe_list:
    print(dataframe.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 13 columns):
Year         5 non-null int64
January      5 non-null float64
February     5 non-null float64
March        5 non-null float64
April        5 non-null float64
May          5 non-null float64
June         5 non-null float64
July         5 non-null float64
August       5 non-null float64
September    5 non-null float64
October      5 non-null float64
November     5 non-null float64
December     5 non-null float64
dtypes: float64(12), int64(1)
memory usage: 600.0 bytes
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 13 columns):
Year         5 non-null int64
January      5 non-null float64
February     5 non-null float64
March        5 non-null float64
April        5 non-null float64
May          5 non-null float64
June         5 non-null float64
July         5 non-null float64
August       5 non-null float64
September    5 non-null float64
Octob

Loop on columns in pandas dataframes

In [21]:
# Loop through the columns
for column_name in temp_f_1996_to_2000_pd:
    # There's a year column.  We don't want to describe that, so only describe the month columns.
    if column_name in jan_to_december_names[:]:
        print(temp_f_1996_to_2000_pd[column_name].describe())
        print("")

count     5.000000
mean     34.060000
std       3.298939
min      29.700000
25%      31.300000
50%      36.400000
75%      36.400000
max      36.500000
Name: January, dtype: float64

count     5.000000
mean     38.000000
std       3.724916
min      32.800000
25%      36.400000
50%      37.700000
75%      41.000000
max      42.100000
Name: February, dtype: float64

count     5.000000
mean     42.200000
std       3.760319
min      37.900000
25%      38.700000
50%      42.900000
75%      45.500000
max      46.000000
Name: March, dtype: float64

count     5.000000
mean     47.080000
std       3.650616
min      42.800000
25%      44.500000
50%      46.500000
75%      50.400000
max      51.200000
Name: April, dtype: float64

count     5.0000
mean     58.3400
std       1.9995
min      55.6000
25%      57.4000
50%      58.8000
75%      58.9000
max      61.0000
Name: May, dtype: float64

count     5.000000
mean     65.540000
std       2.157081
min      62.100000
25%      64.800000
50%      66.5

Write a function that calculates the mean across the columns of a numpy array:

In [22]:
def column_mean(array_in):
    '''
    Calculates the mean of the columns of a numpy array
    Parameters
    ----------
    array_in : numpy 2-d array
        Input array
    Returns
    ----------
    numpy 1-d array
        The mean of the columns
    '''
    return np.mean(array_in, axis=0)

Run the function on precip_mm_1993_to_1997

In [25]:
# Run the column_mean function on precip_mm_1993_to_1997
precip_mm_1993_to_1997_mean = column_mean(precip_mm_1993_to_1997)
print(precip_mm_1993_to_1997_mean)

[0.902 1.184 1.608 3.746 3.898 2.96  1.114 2.19  2.444 1.402 1.776 0.468]


### To run the column_mean function on multiple arrays, you need to:
