# Practice Dry Code 

**Author: ** Michael Levis

**Date: ** 08/20/2018

Import python packages needed to access directories and files, download files, use numpy arrays, use pandas dataframes, and plot data.

In [1]:
# import os to access directories and files
import os
# import numpy arrays as np
import numpy as np
# import pandas dataframes as pd
import pandas as pd
# import urllib.request to download files
import urllib.request
# import matplotlib to plot data
import matplotlib.pyplot as plt
# print download of packages successful
print("download of python packages successful")

download of python packages successful


Check current working directory.

In [2]:
# Check current working directory
os.getcwd()

'C:\\Users\\Michael Levis\\earth-analytics-bootcamp\\ea-bootcamp-practice-dry-code'

Change to earth-analytics-bootcamp directory to access data files.

In [3]:
# change to earth-analytics-bootcamp directory
os.chdir("/Users/Michael Levis/earth-analytics-bootcamp/")

Download .csv files of monthly precipitation (inches) from figshare and import the data to numpy arrays to data directory.

In [4]:
# download monthly precipitation in inches for years 1988 to 1992 as monthly-precip-1988-to-1992.csv
urllib.request.urlretrieve (url = "https://ndownloader.figshare.com/files/12807380", filename = "data/monthly-precip-1988-to-1992.csv")
# download monthly precipitation in inches for years 1993 to 1997 as monthly-precip-1993-to-1997.csv
urllib.request.urlretrieve (url = "https://ndownloader.figshare.com/files/12807383", filename = "data/monthly-precip-1993-to-1997.csv")
# print download of packages successful
print("download of .csv files successful")

download of .csv files successful


Import packages into numpy arrays using np.loadtext function, and assigning delimiter (,) for .csv files.

In [5]:
# import .csv files, comma delimited.
monthly_precip_1988_to_1992 = np.loadtxt(fname = "/Users/Michael Levis/earth-analytics-bootcamp/data/monthly-precip-1988-to-1992.csv", delimiter = ",")
monthly_precip_1993_to_1997 = np.loadtxt(fname = "/Users/Michael Levis/earth-analytics-bootcamp/data/monthly-precip-1993-to-1997.csv", delimiter = ",")
# print numpy arrays
monthly_precip_1988_to_1992, monthly_precip_1993_to_1997

(array([[0.4 , 1.14, 2.53, 1.48, 3.7 , 0.7 , 0.71, 1.33, 2.02, 0.03, 0.75,
         2.16],
        [1.19, 1.27, 0.97, 1.95, 2.68, 2.93, 1.43, 1.63, 3.54, 1.4 , 0.09,
         1.54],
        [1.04, 1.32, 4.55, 2.16, 1.73, 0.39, 4.23, 1.13, 1.84, 0.96, 1.6 ,
         0.75],
        [1.05, 0.15, 0.43, 2.41, 2.9 , 3.59, 3.11, 2.08, 1.21, 0.93, 3.3 ,
         0.01],
        [0.67, 0.  , 5.17, 0.46, 1.7 , 0.96, 1.13, 3.08, 0.02, 0.79, 2.56,
         0.84]]),
 array([[0.25, 0.9 , 2.15, 2.56, 1.73, 3.38, 1.4 , 1.04, 3.32, 2.42, 2.17,
         0.55],
        [0.86, 1.37, 1.61, 3.46, 1.35, 0.93, 0.35, 2.56, 0.54, 1.02, 2.25,
         0.49],
        [0.64, 1.53, 1.21, 5.45, 9.59, 4.03, 0.72, 1.45, 2.96, 0.59, 1.51,
         0.25],
        [1.89, 0.29, 2.16, 1.49, 4.63, 2.77, 1.96, 0.63, 3.48, 0.28, 1.43,
         0.37],
        [0.87, 1.83, 0.91, 5.77, 2.19, 3.69, 1.14, 5.27, 1.92, 2.7 , 1.52,
         0.68]]))

Download .csv files of monthly temperature in Fahrenheit and import the data to pandas dataframes.

In [6]:
# download csv files from figshare using urllib.request
urllib.request.urlretrieve(url = "https://ndownloader.figshare.com/files/12807389", filename = "data/temp-1991-to-1995-months.csv")
urllib.request.urlretrieve(url = "https://ndownloader.figshare.com/files/12807386", filename = "data/temp-1996-to-2000-months.csv")
# print download successful
print("download of files successful")

download of files successful


Import data to pandas dataframes and print output

In [7]:
# import to pandas dataframes
temp_1991_to_1995 = pd.read_csv("/Users/Michael Levis/earth-analytics-bootcamp/data/temp-1991-to-1995-months.csv")
temp_1996_to_2000 = pd.read_csv("/Users/Michael Levis/earth-analytics-bootcamp/data/temp-1996-to-2000-months.csv")
# print dataframe temp_1991_to_1995
temp_1991_to_1995

Year  January  February  March  April   May  June  July  August  September  \
0  1991     29.9      40.9   42.8   47.8  58.2  66.6  70.5    69.2       61.7   
1  1992     35.9      40.6   43.3   54.3  59.1  62.9  68.3    66.3       64.4   
2  1993     28.3      30.6   42.4   47.6  57.5  64.5  69.5    67.3       58.8   
3  1994     35.5      31.9   43.9   47.6  60.8  70.0  71.2    70.9       65.0   
4  1995     34.5      38.3   42.1   45.1  50.9  62.4  70.5    74.0       60.4   

   October  November  December  
0     52.1      36.8      35.3  
1     54.1      34.1      29.2  
2     48.7      35.6      35.4  
3     50.6      36.6      36.1  
4     50.5      45.0      36.3

In [8]:
# print dataframe temp_1996_to_2000
temp_1996_to_2000

Year  January  February  March  April   May  June  July  August  September  \
0  1996     29.7      37.7   37.9   50.4  58.9  66.9  71.5    69.5       60.8   
1  1997     31.3      32.8   45.5   42.8  57.4  66.5  71.4    68.7       64.0   
2  1998     36.5      36.4   38.7   46.5  58.8  62.1  72.8    70.7       67.1   
3  1999     36.4      42.1   46.0   44.5  55.6  64.8  73.5    69.3       58.5   
4  2000     36.4      41.0   42.9   51.2  61.0  67.4  74.7    73.0       63.1   

   October  November  December  
0     53.1      40.6      36.5  
1     52.7      37.9      33.9  
2     50.4      44.0      32.2  
3     51.9      48.0      36.9  
4     49.6      31.4      31.2

*Question 1*

Select the second row of data (including all columns) from the numpy array containing the data for 1988 to 1992, and save to a new numpy array.

Second row is row index 1 and corresponds with year 1989. Selection includes data in all columns, so there is no value given for column index.

In [9]:
# identify second row of data and save as numpy array precip_1989
precip_1989 = np.array([monthly_precip_1988_to_1992[1,]])
# print array
precip_1989

array([[1.19, 1.27, 0.97, 1.95, 2.68, 2.93, 1.43, 1.63, 3.54, 1.4 , 0.09,
        1.54]])

*Question 2*

Write a conditional statement that checks whether the numpy array created in the previous question (i.e. the selection) is a one-dimensional numpy array.

Apply .ndim function to new array precip_1989 with conditional statement to verify dimensions. Print results based on whether it is one dimensional.

In [10]:
# write another conditional statement to verify that array monthly_precip_1989 is one dimensional
if precip_1989.ndim == 1:
    print("this is a one dimensional array")
else:
    print("this is not a one dimensional array")

this is not a one dimensional array


*Question 3*

Modify your conditional statement from the previous question, so that your if and else statements execute different code, not just printing messages.

Create variable x to equal number of dimensions in array precip_1989. Apply conditional statement to execute code based on the outcome. If the number of dimensions equal 1, print the shape of the data. If the number of dimensions are more than 1, apply  function to flatten array to create a new array.

In [11]:
# create variable for precip_1989.ndim
x = precip_1989.ndim
# write conditional statement to verify that array precip_1989 is one dimensional
if x in precip_1989 == 1:
    print(precip_1989.shape)
else:
    precip_1989_1d = precip_1989.flatten()
    print(precip_1989_1d.shape)

(12,)


*Question 4:*

Manually create a one-dimensional numpy array that contains the month names (i.e. January to December). Write a conditional statement to check that this new array for month names has the same shape as the numpy array from the previous question (i.e. the selection).

Print a message stating whether are not these arrays have the same shape and can be plotted together.

Create numpy array of months from January to December upon which to iterate. Apply shape function to month list and one dimensional array for precipitation in 1989. Print message depending on whether the shapes match.

In [12]:
# create list of months
monthlist = np.array(["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"])
# write conditional statement to verify that monthlist has same shape as precip_1989_1d
if monthlist.shape == precip_1989_1d.shape:
    print("the arrays have the same shape and can be plotted together")
else:
    print("the arrays do not have the same shape and cannot be plotted together")

the arrays have the same shape and can be plotted together


*Question 5:*

Write a sentence or two on how you could expand on your conditional statement from the previous question to create a plot from the two numpy arrays if they do indeed have the same shape.

Create variable containing the arrays monthlist and precip_1989_1d. Write a conditional statement with instructions to create a plot if the arrays match. Otherwise, the function to flatten the data could be applied before plotting.  Additionally, a function could be made to create the plot, which could be applied in both scenarios instead of writing out the entire  

*Question 6: Loop on Pandas Dataframes*

Write a loop to run the info() method on the two pandas dataframes that you imported in this activity, and print the results.

Create list dataframe_list of the two pandas dataframes with temperature data. Write loop to apply the .info function to all dataframes in the list.

In [13]:
# create list of pandas dataframes
dataframe_list = [temp_1991_to_1995, temp_1996_to_2000]
# execute loop to print info for each dataframe
for dataframe in dataframe_list:
    print(dataframe.info())
    print("")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 13 columns):
Year         5 non-null int64
January      5 non-null float64
February     5 non-null float64
March        5 non-null float64
April        5 non-null float64
May          5 non-null float64
June         5 non-null float64
July         5 non-null float64
August       5 non-null float64
September    5 non-null float64
October      5 non-null float64
November     5 non-null float64
December     5 non-null float64
dtypes: float64(12), int64(1)
memory usage: 600.0 bytes
None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 13 columns):
Year         5 non-null int64
January      5 non-null float64
February     5 non-null float64
March        5 non-null float64
April        5 non-null float64
May          5 non-null float64
June         5 non-null float64
July         5 non-null float64
August       5 non-null float64
September    5 non-null float64
Octo

*Question 7: Loop on Columns in Pandas Dataframes
Write a loop to run the .describe() method on each column in the pandas dataframe containing the data for 1996 to 2000).*

In [14]:
print(temp_1996_to_2000.describe())

              Year    January   February      March      April      May  \
count     5.000000   5.000000   5.000000   5.000000   5.000000   5.0000   
mean   1998.000000  34.060000  38.000000  42.200000  47.080000  58.3400   
std       1.581139   3.298939   3.724916   3.760319   3.650616   1.9995   
min    1996.000000  29.700000  32.800000  37.900000  42.800000  55.6000   
25%    1997.000000  31.300000  36.400000  38.700000  44.500000  57.4000   
50%    1998.000000  36.400000  37.700000  42.900000  46.500000  58.8000   
75%    1999.000000  36.400000  41.000000  45.500000  50.400000  58.9000   
max    2000.000000  36.500000  42.100000  46.000000  51.200000  61.0000   

            June       July     August  September    October   November  \
count   5.000000   5.000000   5.000000   5.000000   5.000000   5.000000   
mean   65.540000  72.780000  70.240000  62.700000  51.540000  40.380000   
std     2.157081   1.391761   1.705286   3.258067   1.497665   6.285062   
min    62.100000  71.400

In [15]:
columnlist = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
for column in columnlist:
    print(temp_1996_to_2000[[column]].describe())

         January
count   5.000000
mean   34.060000
std     3.298939
min    29.700000
25%    31.300000
50%    36.400000
75%    36.400000
max    36.500000
        February
count   5.000000
mean   38.000000
std     3.724916
min    32.800000
25%    36.400000
50%    37.700000
75%    41.000000
max    42.100000
           March
count   5.000000
mean   42.200000
std     3.760319
min    37.900000
25%    38.700000
50%    42.900000
75%    45.500000
max    46.000000
           April
count   5.000000
mean   47.080000
std     3.650616
min    42.800000
25%    44.500000
50%    46.500000
75%    50.400000
max    51.200000
           May
count   5.0000
mean   58.3400
std     1.9995
min    55.6000
25%    57.4000
50%    58.8000
75%    58.9000
max    61.0000
            June
count   5.000000
mean   65.540000
std     2.157081
min    62.100000
25%    64.800000
50%    66.500000
75%    66.900000
max    67.400000
            July
count   5.000000
mean   72.780000
std     1.391761
min    71.400000
25%    71.50000

In [16]:
columnlist = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
for column in columnlist:
    temp = temp_1996_to_2000[[column]]
    print(temp.describe())

         January
count   5.000000
mean   34.060000
std     3.298939
min    29.700000
25%    31.300000
50%    36.400000
75%    36.400000
max    36.500000
        February
count   5.000000
mean   38.000000
std     3.724916
min    32.800000
25%    36.400000
50%    37.700000
75%    41.000000
max    42.100000
           March
count   5.000000
mean   42.200000
std     3.760319
min    37.900000
25%    38.700000
50%    42.900000
75%    45.500000
max    46.000000
           April
count   5.000000
mean   47.080000
std     3.650616
min    42.800000
25%    44.500000
50%    46.500000
75%    50.400000
max    51.200000
           May
count   5.0000
mean   58.3400
std     1.9995
min    55.6000
25%    57.4000
50%    58.8000
75%    58.9000
max    61.0000
            June
count   5.000000
mean   65.540000
std     2.157081
min    62.100000
25%    64.800000
50%    66.500000
75%    66.900000
max    67.400000
            July
count   5.000000
mean   72.780000
std     1.391761
min    71.400000
25%    71.50000

*Question 8: Write Function to Summarize Numpy Array Using Axes
Write a function that calculates the mean across columns of a numpy array.*

In [17]:
# write function to calculate mean across columns
def mean_column(x):
    x = np.mean(x, axis = 0)
    return(x)

*Question 9: Execute Function and Save Output to New Numpy Array
Run the function created in the previous question (i.e. to calculate mean of columns in a numpy array) on the numpy array containing data for 1993 to 1997. Save the output to a new numpy array.*

In [18]:
# apply function to monthly_precip_1993_to_1997 to create new array mean_precip 
mean_precip = mean_column(monthly_precip_1993_to_1997)
# print output
mean_precip

array([0.902, 1.184, 1.608, 3.746, 3.898, 2.96 , 1.114, 2.19 , 2.444,
       1.402, 1.776, 0.468])

*Question 10: Practice Pseudo Coding
You have already learned how to save the output from one run of a function (see Question 9). What if you wanted to run the function on multiple numpy arrays?

Create empty list on which to add values calculated in the loop. Write a "for" loop to run the function mean_column and add the items to the new list.