# Hands-on Practice Writing DRY Code

* ** Author: ** Nan Rosenbloom
* ** Date: ** August 21, 2018

### Importing software 

In [1]:
# Download the software packages I need

import os
import numpy as np
import pandas as pd
import urllib.request
import matplotlib.pyplot as plt

# confirm that packages installed correctly
print("all packages imported.")

all packages imported.


### Set working directory

In [3]:
# setting working directory
os.chdir("/Users/nanr/work/earth-analytics-bootcamp/")

# confirm working directory
os.getcwd()

'/Users/nanr/work/earth-analytics-bootcamp'

### Download precip datasets:

In [6]:
# use `urllib` download files from Earth Lab figshare repository

# download .csv containing monthly average temperature for Boulder, CO (2004-2009)
urllib.request.urlretrieve(url = "https://ndownloader.figshare.com/files/12807380", 
                           filename = "data/monthly-precip-1988-to-1992.csv")

# download .csv containing monthly average temperature for Boulder, CO (2004-2009)
urllib.request.urlretrieve(url = "https://ndownloader.figshare.com/files/12807383", 
                           filename = "data/monthly-precip-1993-to-1997.csv")

# confirm that all datasets downloaded
print("successfully downloaded precip csv files")

successfully downloaded precip csv files


### Read precip data into numpy arrays

In [13]:
# load two csv precip files into numpy arrays
precip_1988_to_1992 = np.loadtxt(fname = "data/monthly-precip-1988-to-1992.csv",delimiter=",")
precip_1993_to_1997 = np.loadtxt(fname = "data/monthly-precip-1993-to-1997.csv",delimiter=",")

## Download temperature datasets:

In [14]:
# use `urllib` download files from Earth Lab figshare repository

# download .csv containing monthly average temperature for Boulder, CO (2004-2009)
urllib.request.urlretrieve(url = "https://ndownloader.figshare.com/files/12807389", 
                           filename = "data/temp-1991-to-1995-months.csv")

# download .csv containing monthly average temperature for Boulder, CO (2004-2009)
urllib.request.urlretrieve(url = "https://ndownloader.figshare.com/files/12807386", 
                           filename = "data/temp-1996-to-2000-months.csv")

# confirm that all datasets downloaded
print("successfully downloaded temperature csv files")

successfully downloaded temperature csv files


## Read temperature datasets into pandas dataframes:

In [16]:
# read temperature datasets into pandas dataframes
temp_1991_to_1995 = pd.read_csv("data/temp-1991-to-1995-months.csv")
temp_1996_to_2000 = pd.read_csv("data/temp-1996-to-2000-months.csv")

In [18]:
print(precip_1988_to_1992)
print(precip_1993_to_1997)
print(temp_1991_to_1995)
print(temp_1996_to_2000)

[[0.4  1.14 2.53 1.48 3.7  0.7  0.71 1.33 2.02 0.03 0.75 2.16]
 [1.19 1.27 0.97 1.95 2.68 2.93 1.43 1.63 3.54 1.4  0.09 1.54]
 [1.04 1.32 4.55 2.16 1.73 0.39 4.23 1.13 1.84 0.96 1.6  0.75]
 [1.05 0.15 0.43 2.41 2.9  3.59 3.11 2.08 1.21 0.93 3.3  0.01]
 [0.67 0.   5.17 0.46 1.7  0.96 1.13 3.08 0.02 0.79 2.56 0.84]]
[[0.25 0.9  2.15 2.56 1.73 3.38 1.4  1.04 3.32 2.42 2.17 0.55]
 [0.86 1.37 1.61 3.46 1.35 0.93 0.35 2.56 0.54 1.02 2.25 0.49]
 [0.64 1.53 1.21 5.45 9.59 4.03 0.72 1.45 2.96 0.59 1.51 0.25]
 [1.89 0.29 2.16 1.49 4.63 2.77 1.96 0.63 3.48 0.28 1.43 0.37]
 [0.87 1.83 0.91 5.77 2.19 3.69 1.14 5.27 1.92 2.7  1.52 0.68]]
   Year  January  February  March  April   May  June  July  August  September  \
0  1991     29.9      40.9   42.8   47.8  58.2  66.6  70.5    69.2       61.7   
1  1992     35.9      40.6   43.3   54.3  59.1  62.9  68.3    66.3       64.4   
2  1993     28.3      30.6   42.4   47.6  57.5  64.5  69.5    67.3       58.8   
3  1994     35.5      31.9   43.9   47.6  60

### Question 1: Use Indexing to Select from Numpy Array
Select the second row of data (including all columns) from the numpy array containing the data for 1988 to 1992, and save to a new numpy array.

Name your new array appropriately to indicate the year of data that it represents.

In [36]:
precip_1989 = np.array(precip_1988_to_1992[1:2,0:12])

In [37]:
print(precip_1989)

[[1.19 1.27 0.97 1.95 2.68 2.93 1.43 1.63 3.54 1.4  0.09 1.54]]


In [38]:
print(type(precip_1989))

<class 'numpy.ndarray'>


### Question 2: Write a Conditional Statement to Check Dimensions of Numpy Array
Write a conditional statement that checks whether the numpy array created in the previous question (i.e. the selection) is a one-dimensional numpy array.

Print a message stating whether or not the array is one-dimensional.



In [40]:
# checking if data array is 1D or not.
if precip_1989.ndim == 1:
    print("precip_1989 is a 1D array")
else:
    print("precip_1989 is NOT a 1D array")

precip_1989 is NOT a 1D array


In [41]:
print(precip_1989.ndim)

2


In [42]:
precip_1989.shape

(1, 12)

## Question 3: Expand Conditional Statement to Execute Different Code
Modify your conditional statement from the previous question, so that your if and else statements execute different code, not just printing messages.

For the if statement, rather than printing a message, print the shape of the numpy array from the previous question (i.e. the selection).

For the else statement, rather than printing a message, include the following code lines to be executed (i.e. if the array is not one-dimensional):
* arrayname_1d = arrayname.flatten()
* print(arrayname_1d.shape)



In [46]:
# checking if data array is 1D or not.
if precip_1989.ndim == 1:
    precip_1989.shape
else:
    precip_1989_1d = precip_1989.flatten()
    print(precip_1989_1d.shape)

(12,)


## Question 4: Write a Conditional Statement to Check Dimensions of Two Numpy Arrays
Manually create a one-dimensional numpy array that contains the month names (i.e. January to December).

Write a conditional statement to check that this new array for month names has the same shape as the numpy array from the previous question (i.e. the selection).

Print a message stating whether are not these arrays have the same shape and can be plotted together.

In [53]:
# Creating 1D numpy array with names of months:
months = np.array(["January","February","March","April","May","June","July","August","September","October","November","December"])

### Write a conditional statement to compare the two numpy arrays.

In [58]:
if months.shape == precip_1989_1d.shape:
    print("months array and and precip_1989_1d array have the same shape and can be plotted together.")
else:
    print("months array and precip_1989_1d array do NOT have the same shape")

months array and and precip_1989_1d array have the same shape and can be plotted together.


## Question 5: Practice Pseudo Coding
Reflect on your conditional statement from the previous question.

Write a sentence or two on how you could expand on your conditional statement from the previous question to create a plot from the two numpy arrays if they do indeed have the same shape.

Hint: what did you do in Question 3 to expand on your conditional statement?

#### Expand on conditional statement:
To expand on my earlier work I could write a conditional statement that compares the shape of the two arrays, and if they ARE the same shape, I could add a function to plot them (or I could just add the code to plot them) to the body of the conditional statement.

## Question 6: Loop on Pandas Dataframes
Write a loop to run the info() method on the two pandas dataframes that you imported in this activity, and print the results.

In [66]:
# I loop over the two temperature datasets, and running the info() method on each of them.

temp_files = (temp_1996_to_2000,temp_1991_to_1995)
for f in temp_files:
    print(f.info())
    print("")


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 13 columns):
Year         5 non-null int64
January      5 non-null float64
February     5 non-null float64
March        5 non-null float64
April        5 non-null float64
May          5 non-null float64
June         5 non-null float64
July         5 non-null float64
August       5 non-null float64
September    5 non-null float64
October      5 non-null float64
November     5 non-null float64
December     5 non-null float64
dtypes: float64(12), int64(1)
memory usage: 600.0 bytes
None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 13 columns):
Year         5 non-null int64
January      5 non-null float64
February     5 non-null float64
March        5 non-null float64
April        5 non-null float64
May          5 non-null float64
June         5 non-null float64
July         5 non-null float64
August       5 non-null float64
September    5 non-null float64
Octo

## Question 7: Loop on Columns in Pandas Dataframes
Write a loop to run the .describe() method on each column in the pandas dataframe containing the data for 1996 to 2000).

In [89]:
# I loop over the column headers (names of the months) in order to describe each column of data in the pandas array.

# First I create a list of month names:
month_list = ("January","February","March","April","May","June","July","August","September","October","November","December")

# then I loop over the list to isolate the columns.
for m in month_list:
    print(temp_1996_to_2000[[m]].describe())
    print("")
        

         January
count   5.000000
mean   34.060000
std     3.298939
min    29.700000
25%    31.300000
50%    36.400000
75%    36.400000
max    36.500000

        February
count   5.000000
mean   38.000000
std     3.724916
min    32.800000
25%    36.400000
50%    37.700000
75%    41.000000
max    42.100000

           March
count   5.000000
mean   42.200000
std     3.760319
min    37.900000
25%    38.700000
50%    42.900000
75%    45.500000
max    46.000000

           April
count   5.000000
mean   47.080000
std     3.650616
min    42.800000
25%    44.500000
50%    46.500000
75%    50.400000
max    51.200000

           May
count   5.0000
mean   58.3400
std     1.9995
min    55.6000
25%    57.4000
50%    58.8000
75%    58.9000
max    61.0000

            June
count   5.000000
mean   65.540000
std     2.157081
min    62.100000
25%    64.800000
50%    66.500000
75%    66.900000
max    67.400000

            July
count   5.000000
mean   72.780000
std     1.391761
min    71.400000
25%    71

## Question 8: Write Function to Summarize Numpy Array Using Axes
Write a function that calculates the mean across columns of a numpy array.

In [90]:
# First define function to calculate the column-wise mean of a two-dimensional numpy array

def mean_stats_cols(array):
    
    # calculate mean of two-dimensional numpy array for each column
    # function can take a numpy array as input
    # function can not take list or pandas dataframe as input
    
    stat_mean_row = np.mean(array, axis = 0)
    return(stat_mean_row)

## Question 9: Execute Function and Save Output to New Numpy Array
Run the function created in the previous question (i.e. to calculate median of columns in a numpy array) on the numpy array containing data for 1993 to 1997. Save the output to a new numpy array.

In [115]:
# Create a new numpy array containing the monthly mean precip for years 1993-1997.
mean_monthly_precip_1993_1997_climo = np.array(mean_stats_cols(precip_1993_to_1997))

## Question 10: Practice Pseudo Coding
You have already learned how to save the output from one run of a function (see Question 9). What if you wanted to run the function on multiple numpy arrays?

Write a sentence or two on what you would need to know how to do, in order to save the output from a function that is running on multiple arrays in a loop.

### Pseudo coding:
#### Option 1
If I wanted to save the data from calculations on multiple arrays, I would first need to know (1) how many arrays I wanted to loop over, (2) I would need to check that all the arrays were the same dimension (i.e., in this case, that they all had the same number of columns), (3) then I would create a 2D numpy array to hold the output:  the number or rows (axis=0) would equal the number of arrays, the number of columns (axis=1) would hold the number of columns in each input array, (4) I would create a list to hold the array names, then (5) I would loop over the list, incrementing the output array.

#### OR .... Option 2
I could append each value piecewise to the list of answers.  In which case I could loop through the output of the array function, and add the answers to a new list.  Not sure that it would be easy to keep track of what I was adding unless I could add each returned array to a new line of a numpy array.

Not sure I understand this question very well.

In [120]:
a = ([1,2,3])
b = ([4,5,6])
c = ([7,8,9])
a.append(b[0])
a.append(b[1])
#a.append(c)
print(a)


[1, 2, 3, 4, 5]
