## Practice Dry Code

**author** Shannon White

**date** Aug 21 


import necessary packages

In [1]:
import os
import numpy as np
import urllib.request
import pandas as pd 
import matplotlib.pyplot as plt


download .csv files of **monthly precipitation (inches)** and import the data to **numpy arrays**:

In [2]:
os.getcwd()

'/Users/shannonwhite/earth-analytics-bootcamp/ea-bootcamp-practice-dry-code'

In [5]:
os.chdir('/Users/shannonwhite/earth-analytics-bootcamp/')
os.getcwd()

'/Users/shannonwhite/earth-analytics-bootcamp'

In [7]:
urllib.request.urlretrieve (url="https://ndownloader.figshare.com/files/12807380", filename= "data/monthly-precip-1988-to-1992.csv")
urllib.request.urlretrieve (url="https://ndownloader.figshare.com/files/12807383", filename="data/monthly-precip-1993-to-1997.csv")

('data/monthly-precip-1993-to-1997.csv',
 <http.client.HTTPMessage at 0x1130cd668>)

In [42]:
monthly_precip_1988_to_1992 = np.loadtxt (fname="/users/shannonwhite/earth-analytics-bootcamp/data/monthly-precip-1988-to-1992.csv" , delimiter = ",")
monthly_precip_1993_to_1997 = np.loadtxt (fname="/users/shannonwhite/earth-analytics-bootcamp/data/monthly-precip-1993-to-1997.csv" , delimiter = ",")

In [43]:
print (monthly_precip_1988_to_1992)
print (monthly_precip_1988_to_1992)

[[0.4  1.14 2.53 1.48 3.7  0.7  0.71 1.33 2.02 0.03 0.75 2.16]
 [1.19 1.27 0.97 1.95 2.68 2.93 1.43 1.63 3.54 1.4  0.09 1.54]
 [1.04 1.32 4.55 2.16 1.73 0.39 4.23 1.13 1.84 0.96 1.6  0.75]
 [1.05 0.15 0.43 2.41 2.9  3.59 3.11 2.08 1.21 0.93 3.3  0.01]
 [0.67 0.   5.17 0.46 1.7  0.96 1.13 3.08 0.02 0.79 2.56 0.84]]
[[0.4  1.14 2.53 1.48 3.7  0.7  0.71 1.33 2.02 0.03 0.75 2.16]
 [1.19 1.27 0.97 1.95 2.68 2.93 1.43 1.63 3.54 1.4  0.09 1.54]
 [1.04 1.32 4.55 2.16 1.73 0.39 4.23 1.13 1.84 0.96 1.6  0.75]
 [1.05 0.15 0.43 2.41 2.9  3.59 3.11 2.08 1.21 0.93 3.3  0.01]
 [0.67 0.   5.17 0.46 1.7  0.96 1.13 3.08 0.02 0.79 2.56 0.84]]


download the .csv files of **monthly temperature (Fahrenheit)** and import the data to **pandas dataframes**:

In [12]:
os.getcwd()

'/Users/shannonwhite/earth-analytics-bootcamp'

In [13]:
urllib.request.urlretrieve (url="https://ndownloader.figshare.com/files/12807389", filename="data/temp-1991-to-1995-months.csv")
urllib.request.urlretrieve (url="https://ndownloader.figshare.com/files/12807386", filename="data/temp-1996-to-2000-months.csv")

('data/temp-1996-to-2000-months.csv', <http.client.HTTPMessage at 0x10dcbf550>)

In [14]:
temp_1991_to_1995_months = pd.read_csv("/users/shannonwhite/earth-analytics-bootcamp/data/temp-1991-to-1995-months.csv")
temp_1996_to_2000_months = pd.read_csv("/users/shannonwhite/earth-analytics-bootcamp/data/temp-1996-to-2000-months.csv")

Select the second row **(index = 1)** of data (including all columns) from the numpy array containing the data for 1988 to 1992, and save to a new numpy array.

In [22]:
#start/include index 1(row 2), not include index 2(row 3) ; all columns

monthly_precip_1989 = monthly_precip_1988_to_1992[1:2,0:]
print (monthly_precip_1989)
print (monthly_precip_1989.ndim)

[[0.86 1.37 1.61 3.46 1.35 0.93 0.35 2.56 0.54 1.02 2.25 0.49]]
2


Write a conditional statement that checks whether the numpy array created in the previous question (i.e. the selection) is a one-dimensional numpy array.

In [23]:
if monthly_precip_1989.ndim == 1:
    print ("it is one-dimensional")
else: 
    print("it is not one-dimensional")

it is not one-dimensional


For the **if** statement, rather than printing a message, print the shape of the numpy array from the previous question (i.e. the selection).

For the **else** statement, rather than printing a message, include the following code lines to be executed (i.e. if the array is not one-dimensional):

arrayname_1d = arrayname.flatten()
print(arrayname_1d.shape)

In [25]:
if monthly_precip_1989.ndim == 1:
    print ("monthly_precip_1989.shape")
else: 
    monthly_precip_1989_1d = monthly_precip_1989.flatten()
    print(monthly_precip_1989_1d)
    
print (monthly_precip_1989_1d.shape)

[0.86 1.37 1.61 3.46 1.35 0.93 0.35 2.56 0.54 1.02 2.25 0.49]
(12,)


Write a Conditional Statement to Check Dimensions of Two Numpy Arrays.

**Manually create** a one-dimensional numpy array that contains the month names (i.e. January to December).

Write a conditional statement to *check that this new array for month names has the same* **shape** *as the numpy array from the previous question (monthly_precip_1989_1d)*.

Print a message stating whether are not these arrays have the same shape and can be plotted together.



In [27]:
months = np.array(["Jan", "Feb", "March", "April", "May","June", "July", "Aug", "Sept", "Oct", "Nov", "Dec"])
print (months.shape)

if months.shape==monthly_precip_1989_1d.shape :
    print ("they have the same shape")
else:
    print ("they do not have the same shape")

(12,)
they have the same shape


Write a sentence or two on how you could expand on your conditional statement from the previous question to create a plot from the two numpy arrays if they do indeed have the same shape.

* instead of printing "they have the same shape" one could include the sequence of code for creating a plot. The else statement could print the individual shapes of each dataset ( monthly_precip_1989_1d.shape , months.shape )

Write a loop to run the info() method on the two pandas dataframes that you imported in this activity, and print the results.

In [28]:
print (temp_1991_to_1995_months)
print ("")
print (temp_1996_to_2000_months)

   Year  January  February  March  April   May  June  July  August  September  \
0  1991     29.9      40.9   42.8   47.8  58.2  66.6  70.5    69.2       61.7   
1  1992     35.9      40.6   43.3   54.3  59.1  62.9  68.3    66.3       64.4   
2  1993     28.3      30.6   42.4   47.6  57.5  64.5  69.5    67.3       58.8   
3  1994     35.5      31.9   43.9   47.6  60.8  70.0  71.2    70.9       65.0   
4  1995     34.5      38.3   42.1   45.1  50.9  62.4  70.5    74.0       60.4   

   October  November  December  
0     52.1      36.8      35.3  
1     54.1      34.1      29.2  
2     48.7      35.6      35.4  
3     50.6      36.6      36.1  
4     50.5      45.0      36.3  

   Year  January  February  March  April   May  June  July  August  September  \
0  1996     29.7      37.7   37.9   50.4  58.9  66.9  71.5    69.5       60.8   
1  1997     31.3      32.8   45.5   42.8  57.4  66.5  71.4    68.7       64.0   
2  1998     36.5      36.4   38.7   46.5  58.8  62.1  72.8    70.7     

In [38]:
columnlist = temp_1991_to_1995_months[["January"]], temp_1991_to_1995_months[["February"]], temp_1991_to_1995_months [["March"]], temp_1991_to_1995_months[["April"]], temp_1991_to_1995_months[["May"]], temp_1991_to_1995_months[["June"]], temp_1991_to_1995_months[["July"]], temp_1991_to_1995_months[["August"]],temp_1991_to_1995_months [["September"]], temp_1991_to_1995_months[["October"]],temp_1991_to_1995_months[["November"]], temp_1991_to_1995_months[["December]]"]

for column in columnlist:
    temp_1991_to_1995_months[[column]]=temp_1991_to_1995_months[[column]].info()


SyntaxError: invalid syntax (<ipython-input-38-51f3b435ba44>, line 3)

Write a loop to run the .describe() method on each column in the pandas dataframe containing the data for 1996 to 2000).

Write a function that calculates the mean across columns of a numpy array.

In [41]:
def np_mean_column(array):
    # calculates the mean of columns
    # input are single value variables, decimals, and numpy 
    # input cannot be lists or pandas
    mean_column=np.mean(array,axis=0)
    return (mean_column)


Calculate median of columns in a numpy array on the numpy array containing data for 1993 to 1997. Save the output to a new numpy array

In [45]:
mean_monthly_precip_1993_to_1997 = np_mean_column(monthly_precip_1993_to_1997)
print (mean_monthly_precip_1993_to_1997)

[0.902 1.184 1.608 3.746 3.898 2.96  1.114 2.19  2.444 1.402 1.776 0.468]


Write a sentence or two on what you would need to know how to do, in order to save the output from a function that is running on multiple arrays in a loop.

* the name that is saved as an output of the function would need to contain variables that change. Similar to how the graph was created in homework 3 with "year". You would need to know how to code the output to change the variable in "" as it loops through the arrays. 
